language: node_js
node_js:
- lts/boron
- node
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: lOrR3DSymALxQEuoWpYJ6DkDLVCf3VZdY6htZTfRnH8qcmT83nY4tQM45ZlmaaD4rcLa7O4qdp49uSCxDBC4o/cVlgl3dT8Z7+1PvDEUsr9Ppk63CeIKwgWsh2UFznF/TdX74VqlhzWSM5XCNMlm1ppeDDkzMhXVbv1nBDSI+OI=
  file:
    - "retext-keywords.js"
    - "retext-keywords.min.js"
  on:
    tags: true
